### ISSUE TITLE
Please update website with most recent version of exificient.js.  Thanks!

### ISSUE THREAD

**Issue by coderextreme** [EXIficient/exificient.github.io#1]
This fails to encode and decode properly in JSON <-> EXI:

[-74.01046109936333]

**Comment by danielpeintner** [comment]
Hi,

the demo github.io is just manually synced with the actual library.
The issue should be solved with commit https://github.com/EXIficient/exificient.github.io/commit/4d51babb880d4acb9ca90f4dbf21b18d1d10d1d8.

At the moment floating point numbers are rounded to at most 6 digits. The plan is to provide a call to specify the  number of digits.

Please let us know whether it resolves your issue.

**Comment by coderextreme** [comment]
Yes, I installed the library and it's working fine now.

**Comment by danielpeintner** [comment]
Great! Will close the issue then...
